name: Build Zenora WSL Appx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      DISTRO_NAME: Zenora
      EXE_NAME: launcher.exe
      CONFIGURATION: Release
      ROOTFS_URL: https://github.com/zenoralinux/wsl-zenora-rootfs/releases/download/20250603-0835/zenora-wsl-rootfs.tar.gz

    steps:
      - name: Checkout this repo (for assets and manifest)
        uses: actions/checkout@v3

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Clone WSL-DistroLauncher
        run: |
          git clone https://github.com/microsoft/WSL-DistroLauncher.git
          move WSL-DistroLauncher DistroLauncher

      - name: Download rootfs
        run: |
          Invoke-WebRequest -Uri $env:ROOTFS_URL -OutFile "DistroLauncher\DistroLauncher-Appx\install.tar.gz"

      - name: Copy custom manifest and logo (if exists)
        run: |
          if (Test-Path "AppxManifest.xml") {
            Copy-Item "AppxManifest.xml" -Destination "DistroLauncher\DistroLauncher-Appx\AppxManifest.xml" -Force
          }
          if (Test-Path "logo.png") {
            New-Item -ItemType Directory -Path "DistroLauncher\DistroLauncher-Appx\assets" -Force
            Copy-Item "logo.png" -Destination "DistroLauncher\DistroLauncher-Appx\assets\logo.png" -Force
          }

      - name: Build launcher.exe
        working-directory: ./DistroLauncher
        run: msbuild DistroLauncher.sln /p:Configuration=$env:CONFIGURATION /p:Platform=x64

      - name: Copy launcher to Appx folder
        run: Copy-Item "DistroLauncher\x64\$env:CONFIGURATION\launcher.exe" -Destination "DistroLauncher\DistroLauncher-Appx\"

      - name: Stage files for appx
        run: |
          mkdir AppxStage
          Copy-Item -Recurse "DistroLauncher\DistroLauncher-Appx\*" AppxStage

      - name: Generate PRI files
        run: |
          makepri new /ProjectRoot AppxStage /ConfigXml AppxStage\AppxManifest.xml /OutputFile AppxStage\resources.pri

      - name: Create .appx package
        run: |
          makeappx pack /d AppxStage /p Zenora.appx

      # Optional: Sign the appx (if cert available)
      # - name: Sign Appx (optional)
      #   run: |
      #     signtool sign /fd SHA256 /a /f cert.pfx /p ${{ secrets.CERT_PASSWORD }} Zenora.appx

      - name: Upload built Appx
        uses: actions/upload-artifact@v4
        with:
          name: zenora-appx
          path: Zenora.appx
