name: Build Zenora WSL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build launcher.exe
      run: msbuild DistroLauncher\DistroLauncher\DistroLauncher.vcxproj /p:Configuration=Release /p:Platform=x64

    - name: Upload launcher.exe only
      uses: actions/upload-artifact@v3
      with:
        name: zenora-launcher-exe
        path: DistroLauncher\DistroLauncher\x64\Release\launcher.exe

    - name: Create zip with launcher + rootfs
      shell: pwsh
      run: |
        Compress-Archive -Path `
          DistroLauncher\DistroLauncher\x64\Release\launcher.exe, `
          DistroLauncher\DistroLauncher\x64\install.tar.gz `
          -DestinationPath zenora-launcher-rootfs.zip

    - name: Upload launcher + rootfs zip
      uses: actions/upload-artifact@v4
      with:
        name: zenora-launcher-rootfs-zip
        path: 'DistroLauncher\DistroLauncher\x64\Release\launcher.exe'
