name: Build Zenora WSL Distro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Download rootfs from GitHub Release
      run: |
        Invoke-WebRequest -Uri "https://github.com/zenoralinux/wsl-zenora-rootfs/releases/download/20250603-0835/zenora-wsl-rootfs.tar.gz" -OutFile "DistroLauncher\x64\install.tar.gz"

    - name: Restore NuGet packages
      run: nuget restore DistroLauncher.sln

    - name: Build the solution
      run: msbuild DistroLauncher.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload APPX package
      uses: actions/upload-artifact@v4
      with:
        name: zenora-wsl-appx
        path: DistroLauncher\DistroLauncher-Appx\x64\Release\DistroLauncher-Appx.appx
