name: Build Zenora WSL Appx

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CONFIGURATION: Release
  ROOTFS_URL: https://github.com/zenoralinux/wsl-zenora-rootfs/releases/download/20250603-0835/zenora-wsl-rootfs.tar.gz

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clone DistroLauncher
      run: git clone https://github.com/microsoft/WSL-DistroLauncher.git

    - name: Download rootfs
      run: |
        New-Item -ItemType Directory -Path "DistroLauncher\DistroLauncher-Appx" -Force
        Invoke-WebRequest -Uri $env:ROOTFS_URL -OutFile "DistroLauncher\DistroLauncher-Appx\install.tar.gz"

    - name: Retarget to available Windows SDK
      run: |
        $proj = "DistroLauncher\DistroLauncher\DistroLauncher.vcxproj"
        (Get-Content $proj) -replace '10.0.16299.0', '10.0.19041.0' | Set-Content $proj

    - name: Build launcher.exe
      working-directory: ./DistroLauncher
      run: |
        msbuild DistroLauncher.sln /p:Configuration=$env:CONFIGURATION /p:Platform=x64

    - name: Create appx package
      run: |
        $appxDir = "DistroLauncher\DistroLauncher-Appx"
        $outputAppx = "ZenoraWSL.appx"
        & "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.19041.0\x64\makeappx.exe" pack `
          /d $appxDir `
          /p $outputAppx

    - name: Upload appx artifact
      uses: actions/upload-artifact@v3
      with:
        name: zenora-wsl-appx
        path: ZenoraWSL.appx
